// src/disputeData.js

const disputeData = [
    {
      "Customer Name": "Travis Weeks",
      "Company": "GOLDMAN SACHS BANK USA",
      "transaction_date": "2024-05-26",
      "Amount": 614.7,
      "State": "CA",
      "Dispute Reason": "Item not as described",
      "Dispute Status": "Approved",
      "transaction_id": "67a5ae2d70c15a68aecaa02439",
      "Complaint ID": "12687507",
      "Consumer Complaint Narrative": "I am filing a complaint regarding a disputed charge of {$970.00} on my Apple Card related to Apples XXXX Replacement program for my XXXX XXXX XXXX. Initially, I disputed this charge as unauthorized ( fraud ), but upon further investigation, I realized it was connected to the replacement device I received through the program. Despite returning the defective device as instructed, using the prepaid XXXX label Apple provided, I was charged. XXXX tracking confirms that the package was picked up and processed. However, the device was not delivered to Apple, and I was subsequently charged. Below are the details of the dispute and my efforts to resolve this matter.   Complaint Details Transaction Date : XX/XX/year> Merchant : Apple Store Disputed Amount : {$970.00} Dispute Case Number : XXXX Temporary Credit Provided : {$970.00} ( later reversed ) Timeline of Events I initiated an Express Replacement through Apple for XXXX XXXX XXXX XXXX, which required me to return the defective device to avoid being charged. Apple provided a prepaid XXXX return label for the process.  On XX/XX/year>, I packaged the defective device and dropped it off at a local FedEx facility.  XXXX tracking number XXXX confirms that the package was picked up at the XXXX, TX facility on XX/XX/year>, fulfilling my obligation to return the device.  On XX/XX/year>, I was charged {$970.00}, which I initially disputed as an unauthorized ( fraudulent ) charge because I did not immediately recognize its connection to the XXXX Replacement program.  Upon realizing the charge was related to the XXXX Replacement, I investigated further and confirmed through XXXX tracking that the returned device had not been delivered to Apple.  I contacted XXXX, but they refused to open an investigation because I am not the merchant account holder ( Apple ).  Efforts to Resolve Contact with Apple : I contacted Apple multiple times to confirm receipt of the returned device. They claimed they have no record of receiving the package and stated it was too late for them to investigate. Apple advised me to file a dispute with my credit card issuer.  Contact with XXXX  : I contacted XXXX to initiate an investigation into the packages whereabouts, but XXXX refused, explaining that only Apple, as the merchant account holder, could request an investigation or claim.  Dispute with Credit Card Issuer : I filed a dispute with my credit card issuer, providing all available evidence, including XXXX tracking documentation and screenshots confirming the package was processed. Despite this, my credit card company reversed the temporary credit, citing insufficient evidence, as neither Apple nor XXXX has provided further documentation.  Supporting Documentation XXXX return receipt with tracking number XXXX.  Screenshot of the XXXX tracking history, confirming the package was picked up and remains undelivered.",
      "PayeeID": "d6fafe4dfcf5fa3adeacb7e2"
    },
    {
      "Customer Name": "Ann Bryant",
      "Company": "Bread Financial Holdings, Inc.",
      "transaction_date": "2024-09-06",
      "Amount": 875.78,
      "State": "TX",
      "Dispute Reason": "Item not as described",
      "Dispute Status": "Approved",
      "transaction_id": "67765dcf1c6afc75c33ddfcf9c",
      "Complaint ID": "11014920",
      "Consumer Complaint Narrative": "Around XX/XX/XXXX, I made a purchase of Jewelry of about {$6000.00}. Three weeks later, I returned it for a full refund. A few days later I called and cancelled the card, but noted there was interest of {$31.00} ( ttl fees charged in'XXXX= {$12.00}, ttl interest charged in'XXXX= {$19.00} ) .I was assured by the agent nothing was due, since that time I have received a bill that shows New Balance {$31.00} Min Pmt the words : DO NOT PAY.  Today XX/XX/XXXX, I want the statement to stop and asked why this amt still shows, the answer provided was that ( 1 ) we charged interest. I asked if the account is on 30 day cycle and the product was returned within 21 days, what are you charging interest on? He kept repeating \" we charged interest '' I simply need that amt removed to my \" closed account '' and a letter acknowledging the account is closed w {$0.00} balance & to have Comenity/XXXX  stop sending statements.",
      "PayeeID": "d6fafe4dfcf5fa3adeacb7e2"
    },
    {
      "Customer Name": "Jordan Baker",
      "Company": "TRANSUNION INTERMEDIATE HOLDINGS, INC.",
      "transaction_date": "2024-11-28",
      "Amount": 1131.1,
      "State": "CA",
      "Dispute Reason": "Subscription cancellation not honored",
      "Dispute Status": "Pending",
      "transaction_id": "67f4beedf066bd08a4d0c3f8ee",
      "Complaint ID": "12698202",
      "Consumer Complaint Narrative": "My information was heisted and this accounts are fraudulent and do not belong to me. I would like these accounts completely removed from all three credit bureaus on my credit report.",
      "PayeeID": "d6fafe4dfcf5fa3adeacb7e2"
    },
    {
      "Customer Name": "Erin Williamson",
      "Company": "EQUIFAX, INC.",
      "transaction_date": "2025-03-05",
      "Amount": 644.44,
      "State": "MS",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Denied",
      "transaction_id": "67bdc5c6281f8403cdddfdcc09",
      "Complaint ID": "12679402",
      "Consumer Complaint Narrative": "Please examine the attached documents. I request the bureau to investigate these accounts, as they inaccurately label me as delinquent despite my consistent punctuality.",
      "PayeeID": "a7f1fed5adccfcdafdac7eab"
    },
    {
      "Customer Name": "Jared Wilson",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2024-12-18",
      "Amount": 800.49,
      "State": "OK",
      "Dispute Reason": "Service not rendered",
      "Dispute Status": "Denied",
      "transaction_id": "67faa4effdbbfd7084fba4e80e",
      "Complaint ID": "12732712",
      "Consumer Complaint Narrative": "On XX/XX/XXXX for XXXX I was staying in XXXXXXXX XXXX  at my family house. I went to the local XXXX at XXXX XXXX XXXX XXXX XXXX XXXX XXXXXXXX and made a {$64.00} purchase upgrading some headphones.   I live in an apartment in XXXXXXXX XXXX  for work ( XXXX XXXX XXXXXXXX XXXX XXXX XXXXXXXX ). The day of the unauthorized charges I was here and at work ( XXXX XXXX XXXX XXXX XXXXXXXX XXXX XXXX XXXXXXXX ).   XXXX week later on XX/XX/XXXX I receive an email and text asking about an unauthorized charge for {$570.00} at XXXX, as well as a {$2700.00} charge. I selected unauthorized and received a phone call from Citi bank fraud department. They opened a case and my charges were temporarily reversed.   My account shows only XXXX of the purchases, and it was for a full loaded XXXX, purchased IN STORE at the XXXX location I was at XXXX week prior. I was not physically in town and could not have possibly made the purchase. The XXXX credit card is linked to my account, so I am assuming that is how I was able to get the digital receipt.   CitiBank XXXX weeks later sent me a letter saying my charges were authorized and that I was responsible for payments. This was during XXXX, and I was back in XXXX to visit family. So I physically went to the XXXX location and spoke to the store XXXX / employee about pulling the cameras and getting information. They said this is a case between CitiBank and myself, that they don't have authority to release footage, but wanted to help me if possible. I have their contacts as witnesses if we need to hear it from employees at the store.   I have since reopened the case with CitiBank according to the rep, but have yet to hear anything back. I am concerned this is going to ruin my credit and am now reaching out to the CFPB in hopes to help dispute this case.   Please call me for any information needed, I would like to get this resolved ASAP. Thank you!",
      "PayeeID": "a7f1fed5adccfcdafdac7eab"
    },
    {
      "Customer Name": "Gerald Davies",
      "Company": "NAVY FEDERAL CREDIT UNION",
      "transaction_date": "2025-01-06",
      "Amount": 1052.62,
      "State": "MO",
      "Dispute Reason": "Overcharged",
      "Dispute Status": "Approved",
      "transaction_id": "673ac9ac3fdddf0bbba58e5ec8",
      "Complaint ID": "11306603",
      "Consumer Complaint Narrative": "XXXX XXXX account number XXXX Navy Federal - account number - XXXX I made payments for these companies. Also my account was supposed to be set up on auto pay. I didnt receive no notification and they reported me as being late. Ill contact them about it. They says nothing we can do about it. They reported to the credit report name sees as late please remove these inaccurate reporting off my credit profile. Also, I told them that this was part of a consumer report data breach.",
      "PayeeID": "a7f1fed5adccfcdafdac7eab"
    },
    {
      "Customer Name": "James Nichols",
      "Company": "SYNCHRONY FINANCIAL",
      "transaction_date": "2024-12-24",
      "Amount": 392.64,
      "State": "FL",
      "Dispute Reason": "Service not rendered",
      "Dispute Status": "Denied",
      "transaction_id": "678abc857eeb780f3fdfd4ca2f",
      "Complaint ID": "12727700",
      "Consumer Complaint Narrative": "Hello, I am contacting you regarding an ongoing issue from XXXX of XXXX. I used a Synchrony Bank credit card for this transaction, and this order was placed on XXXX XXXX.   The issue is that I never received the merchandise as promised ; the XXXX tracking showed it was delivered and signed for by me ; however, I was in a different state at the time of delivery, so there was no way I was able to sign for the package. I contacted the merchant, but they did not want to assist, so I took it a step further and contacted Synchrony with this issue.   Initially the process was smooth ; I provided the bank with documentation proving that I was not home at the time of delivery, that XXXX determined the package was lost, and conversations between XXXX and me showing that the merchant doesn't want to cooperate.   Every time I opened a claim, Synchrony would close the claim out with outdated proof of delivery. When I refuted that evidence with up-to-date documentation, they ignored it and closed the claim again with the outdated documentation. I have spoken to them countless times on the phone and been transferred to their \" top managers, '' but nothing gets resolved.   Attached will be all relevant documentation from my flight itinerary to XXXX chat logs.   Here are all the claim IDs from Synchrony.   XX/XX/XXXX : XXXX XX/XX/XXXX : XXXX XX/XX/XXXX : XXXX XX/XX/XXXX : XXXX XX/XX/XXXX : XXXX Here is the XXXX tracking number ( it's over XXXX  days old, so you can't view it ).  XXXX Companies involved with the issue : Synchrony Bank XXXX XXXX XXXX To summarize documentation, you will find XXXX screenshots of chat logs with XXXX, XXXX email from XXXX, the tracking from the XXXX  site before it expired, and a flight itinerary proving I was not home to sign for the package.   Thank you.",
      "PayeeID": "fefff2e8b7a1fda2796fbc39"
    },
    {
      "Customer Name": "Allison Molina MD",
      "Company": "EQUIFAX, INC.",
      "transaction_date": "2024-09-03",
      "Amount": 1339.42,
      "State": "TX",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Approved",
      "transaction_id": "6724ba0acd9925a36708a8ccfc",
      "Complaint ID": "11358622",
      "Consumer Complaint Narrative": "Please review the attached documents. I request that the bureau initiate an investigation into these accounts erroneously reporting me as late when I have been consistently punctual.",
      "PayeeID": "6ff0f96bc473fbfc9a1faaaa"
    },
    {
      "Customer Name": "William Becker",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2024-07-29",
      "Amount": 204.5,
      "State": "IL",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Approved",
      "transaction_id": "67a6c2268b9d9f55de5b9d1abb",
      "Complaint ID": "8469242",
      "Consumer Complaint Narrative": "I paid Citi XXXX {$3700.00} after they closed my credit card account. XXXX and XXXX XXXX confirmed I paid off the card and the balance is not XXXX. I called XXXX personally and they confirmed Citi confirmed the balance was XXXX and the card was paid off.  Now Citi Card online on their website is stating they didn't get the money and want me to pay payments as they claim there is a balance on the card.   I have called them repeatedly, emailed them and my email comes back undeliverable, talked to their XXXX XXXX  representative and they still claim they didnt get the payment and I own them the full amount or a payment.   My FICO score at XXXX is XXXX so I am not a XXXX XXXX  person reporting on them for no reason.   They want money in XXXX days or they will destroy my credit rating and turn me over to collection for a bill that XXXX confirmed Citi received my payment in full and there is a {$0.00} balance.   Citi refuses to contact XXXX to get the confirmation from Citi saying it was paid in full. Their right hand doesn't know what their left hand is doing and it is causing me great stress. Please contact XXXX and have them tell Citi that they were paid in full like XXXX by email and phone told me. They closed the account as they refused payments many times. Finally, XXXX went through and XXXX confirmed that Citi confirmed the payment in full.",
      "PayeeID": "aef1fa6ef93ff1bd6a1f5446"
    },
    {
      "Customer Name": "Regina Carter",
      "Company": "DISCOVER BANK",
      "transaction_date": "2024-08-08",
      "Amount": 1478.4,
      "State": "NJ",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Pending",
      "transaction_id": "678eb260ed70fb35e3a47b0d9a",
      "Complaint ID": "12690610",
      "Consumer Complaint Narrative": "XX/XX/XXXX sent DISCOVER FINANCIAL SERVICE notice to rescind any written or verbal contracts with my signature. And to return the securities and FRN ( XXXX XXXX XXXX ) payments made over the length of the establishment of this account.  A registered securities was mailed out and accepted on XX/XX/2024, been over 30days.  DISCOVER FINANCIAL SERVICES per CFPB responded with a letter informing me that they will not stop reporting potential harmful information to the public. And will not stop receiving and selling my securities fraudulently, this fraudulent debt thats continuingly collecting interests and principal on my behalf.",
      "PayeeID": "aef1fa6ef93ff1bd6a1f5446"
    },
    {
      "Customer Name": "Misty Gamble",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2024-05-19",
      "Amount": 656.86,
      "State": "OH",
      "Dispute Reason": "Service not rendered",
      "Dispute Status": "Approved",
      "transaction_id": "67efbf973e1d2f20d7b8d7b61c",
      "Complaint ID": "12690614",
      "Consumer Complaint Narrative": "XX/XX/XXXX XX/XX/XXXX XXXX XXXX XX/XX/XXXX XX/XX/XXXX All the following dates have been the same continuing issue. I can purchase a few large purchases roughly between {$500.00} to {$6000.00} which banks enough points to purchase something worth a few XXXX dollars. I will go to purchase something and the card will be declined. Later, without my consent I will receive a new card in the mail, between these times my points will expire. I have called in regards to this on all of the dates I have provided and more. Unfortunately I have not documented all of the instances. Their telephone representatives are extremely rude and will talk over you and interrupt you intentionally attempting to confuse the situation. They will then transfer you to an alleged supervisor through a continual loop until you frustrate and hang up, the longest loop was the second to last phone call which took XXXX XXXX hours I have spent over accumulative XXXX hours on the phone trying to resolve this issue. I own a chain of stores and have purchased hundreds of thousands of dollars of Tech through Best Buy. I feel the system is put to place to avoid allowing people like me to benefit. The last attempt I made I was refused any assistance, and I was not explained to why my card was canceled and a new one was mailed. I will now lose the remaining points I have for {$1600.00} purchase for a drone. Ive never been spoken to like this in my entire life. I believe we will be closing the cards and I will be requesting full reimbursement for all lost points over the last four years accumulating over {$1000.00}.",
      "PayeeID": "aef1fa6ef93ff1bd6a1f5446"
    },
    {
      "Customer Name": "Michael Clements",
      "Company": "BANK OF AMERICA, NATIONAL ASSOCIATION",
      "transaction_date": "2025-01-03",
      "Amount": 1577.57,
      "State": "WA",
      "Dispute Reason": "Subscription cancellation not honored",
      "Dispute Status": "Pending",
      "transaction_id": "678f24fefeaca2588e8ae2abd5",
      "Complaint ID": "12685021",
      "Consumer Complaint Narrative": "XXXX XXXX XXXX XXXX NY {$1400.00} Transaction Date XX/XX/2023 There was an unauthorized order placed on a Bank of America credit card I never received in the mail. The merchant provided an order invoice with the incorrect address and Bank of America is still holding me liable for this transaction. The merchant did not have my apartment number on the orders invoice. I never received anything or dealt with the merchant before. Bank of America is refusing to refund me for a purchase I did not make on a card I never received",
      "PayeeID": "aef1fa6ef93ff1bd6a1f5446"
    },
    {
      "Customer Name": "Mark Harris",
      "Company": "TRANSUNION INTERMEDIATE HOLDINGS, INC.",
      "transaction_date": "2024-11-27",
      "Amount": 629.99,
      "State": "TX",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Denied",
      "transaction_id": "67b39bb89dcfe59d494fe60c7a",
      "Complaint ID": "11789275",
      "Consumer Complaint Narrative": "I am seeking your help to investigate accounts from companies reporting late payments inaccurately. Upon reviewing my credit report, I discovered specific accounts marked with late payments, which is incorrect. There should be no late payment records on these accounts.",
      "PayeeID": "aff7ffdbf72df3e12ce2e542"
    },
    {
      "Customer Name": "Steven Alvarez",
      "Company": "TRANSUNION INTERMEDIATE HOLDINGS, INC.",
      "transaction_date": "2024-05-31",
      "Amount": 967.4,
      "State": "NY",
      "Dispute Reason": "Item not as described",
      "Dispute Status": "Pending",
      "transaction_id": "670abceaf1feba5dd4a9ffa1bd",
      "Complaint ID": "12620435",
      "Consumer Complaint Narrative": "I am writing to dispute a late payment that was recently reported on my credit report. According to my records, the payment was made on time. However, it appears that there is an error in the reporting, and the payment was incorrectly marked as late.",
      "PayeeID": "aff7ffdbf72df3e12ce2e542"
    },
    {
      "Customer Name": "Sarah Mitchell",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2024-06-14",
      "Amount": 32.93,
      "State": "TX",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Approved",
      "transaction_id": "673ca27b0a4afa2cca7de7ffe5",
      "Complaint ID": "11155020",
      "Consumer Complaint Narrative": "I was overcharged {$340.00} for XXXX XXXX performed on XX/XX/XXXX by XXXX XXXX in XXXX XXXX  MO.After 5 months of XXXX, XXXX XXXX called me and informed me on XXXX XXXX, XXXX that they were sending me a check. No check was ever received.   I submitted a fraudent charge complaint on XXXX, XXXX to my credit card company Citibank Mastercard . After hearing nothing, on XX/XX/XXXX I contacted Citibank for a status report. They informed me they had lost my electronically filed complaint and I would now required to file a written hardcopy compaint which I did.  On XX/XX/XXXX I contacted Citibank Mastercard who indicated they had received my hardcopy complaint and would order an expedited response.  On XX/XX/XXXX I again contacted Citibank Mastercard who stated they have no record of any complaint filed before XXXX XXXX, XXXX which is just outside their 6 month time limit for any action on fraudulent credit card losses. I cancelled my credit card in disgust with Citibank 's fraudulent actions regarding my dispute.",
      "PayeeID": "aff7ffdbf72df3e12ce2e542"
    },
    {
      "Customer Name": "David Buckley",
      "Company": "SYNCHRONY FINANCIAL",
      "transaction_date": "2025-03-07",
      "Amount": 1275.58,
      "State": "TN",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Denied",
      "transaction_id": "67160bb0a13ed4c8f2ff4caf7e",
      "Complaint ID": "12314227",
      "Consumer Complaint Narrative": "This is supposed to be a no interest repayment. First they started charging statement fees and charging interest and late fees on those statement fees which they said would stop once I went paperless. The interest continued. Various late fees continued even though my payments were on time. When I called they force me to pay the late fee and tell me on the next bill my payment will be a certain amount. I ensure that amount is received before the due date and I still get late fees every month. It's as if because I was paying as agreed their promotion they're finding ways to steal more than they agreed through the baiting promotion that had me apply and receive the account to begin with at XXXX XXXX XXXX",
      "PayeeID": "cafef1f6adfbf504a50582c8"
    },
    {
      "Customer Name": "Colton Smith",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2025-02-09",
      "Amount": 1280.44,
      "State": "FL",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Approved",
      "transaction_id": "6741141d556d5f8ffdca85d6dc",
      "Complaint ID": "11355015",
      "Consumer Complaint Narrative": "Citibank sent me an email AFTER reducing my credit line. They said that this reduction was due to my credit report, but I almost always pay above the minimum pay on all of my cards. There has not been anything negative on my credit report. I closed one credit card and traded in a car. I was never given an exact reason for this reduction. This reduction also cane after making a substantial payment, thus CAUSING a negative impact to my credit score.",
      "PayeeID": "cafef1f6adfbf504a50582c8"
    },
    {
      "Customer Name": "Joshua Matthews",
      "Company": "FIRST NATIONAL BANK OF OMAHA",
      "transaction_date": "2024-12-18",
      "Amount": 1577.88,
      "State": "IL",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Approved",
      "transaction_id": "67de7bfcf4ae7af34b7d4093be",
      "Complaint ID": "8470063",
      "Consumer Complaint Narrative": "I received a letter from FNBO about my credit card I have with them stating that if I did not enroll in their paperless billing and move my banking online that I would be charged a {$1.00} every month. I called them stating if you moved my information online you not only open me up to financial crimes but identity theft as well as they would put all my information online including my SSN. They couldnt care less. In fact they hung up on me the first time. Either I start banking online or be charged this fee. And as we all know as soon as they add a fee it will be no time until they begin to increase it.",
      "PayeeID": "cafef1f6adfbf504a50582c8"
    },
    {
      "Customer Name": "Jeffrey Wilson",
      "Company": "BANK OF AMERICA, NATIONAL ASSOCIATION",
      "transaction_date": "2024-08-20",
      "Amount": 383.89,
      "State": "MO",
      "Dispute Reason": "Duplicate transaction",
      "Dispute Status": "Approved",
      "transaction_id": "671edaff37eaf4c13edfdff876",
      "Complaint ID": "12500433",
      "Consumer Complaint Narrative": "In XX/XX/2024 I suddenly lost my job due to the company I was working for decided to no longer contract with the client company I was working at and therefore was laid off. Since then I have been struggling to pay all bills as I have been unemployed and only finding work perdiem ( as needed ) so therefore I was not able to make the monthly payments due. I contacted Bank of America credit card customer service to inform them of my financial hardship, but I was informed by a representative that there was nothing that could be done as they dont have any programs for those undergoing financial hardship. The only thing they did was refer me to a XXXX party company ( XXXX XXXX  ) company. I contacted the company and underwent an assessment of expenses I have to pay monthly. After the assessment, I was told that my monthly expenses and bills exceeded my monthly income and just pay what I can afford on the credit card bill until my income status gets better. This did not resolve my issue as the monthly bill increased and APR interest rates increased making it even more difficult to pay. I called back Bank of America credit card company and complained that the company they referred me to did not help me, all the representative of Bank of America did was apologize profusely and that was all, so still my problem remains and I am completely devastated that as a loyal customer of Bank of America for 20plus years they refuse to give me grace and help. This is injustice and a disgrace that Bank of America represents themselves in such a manner. I need help to resolve this issue immediately.",
      "PayeeID": "cafef1f6adfbf504a50582c8"
    },
    {
      "Customer Name": "Dana Taylor",
      "Company": "JPMORGAN CHASE & CO.",
      "transaction_date": "2024-06-14",
      "Amount": 506.28,
      "State": "OH",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Approved",
      "transaction_id": "67d653712e5fba2a71e59b6d0b",
      "Complaint ID": "11230217",
      "Consumer Complaint Narrative": "I had booked a flight through XXXX back on the XXXX of XXXX to go to XXXX XXXX because the tickets were so cheap, only around {$210.00} for a round trip flight. I have a chase sapphire credit card and XXXX is a partner with Chase so I booked the flight through my points. I had transferred over XXXX points that day ( they do immediate point transfer and my points were XXXX plus a bonus 25 % ) and booked my flight. I even had to pay an extra {$9.00} that my points didnt cover and so I checked my Chase app to see if the transaction for the {$9.00} went through and it did, I received a confirmation code for my flight, my seat number and everything you would see if you booked a flight ( I have a screenshot ) as Ive traveled of planes plenty on times in my life. Fast forward to the day Im leaving for my trip I go to check into my flight and my confirmation code is not working. I immediately call XXXX and they inform me that I do not have a ticket!!! I said how is this possible when I bought my ticket over a month ago. They then informed me that the ticket never ticketed ( never knew that was a thing or something that customers need to be aware of or how we would even know if a ticket didnt ticket? ) so they refunded my points into my XXXX account. I never once received an email or any sort of notification that they didnt ticket my ticket and refunded my points. I asked them why the ticket didnt ticket and they couldnt give me a reason. I then said I never received a single notification for this and they were very nonchalant and said I shouldve received an email but I never did, not a text or anything!! They informed me they could SEE my transactions of when I bought my ticket. So I asked if they could just book me another ticket for the price that I had originally paid for the ticket since this is so far beyond my fault and that this was clearly an issue on their end and they informed me they could not and that the tickets were {$730.00} now!!!! My flight was leaving in XXXX hours I was about to leave for the airport when all of this was happening. I fought and fought my way through XXXX different people at XXXX all informing me there was nothing they could do. They didnt offer a single thing, not even a free bag or anything to make up for their mistake. I had everything already booked for my trip so I couldnt not go or Id lose out on even more money. I went ahead and booked the ticket and told them Id be fighting for this because it is so unfair that a CUSTOMER must pay an extra {$470.00} ( keeping in mind thats a lot of money for a customer but not for a massive corporation like XXXX ) for a ticket that I had already booked and received confirmation for over a month ago bc of an issue that was on their end and failed to inform me because obviously if I got an email that my ticket didnt go through I wouldve rebooked another one immediately and the fact that they could see the whole transaction process is proof right to their faces that I had purchased this ticket. I have now fought this transaction with chase. Im only asking for the refund for the extra {$470.00} I had to pay for the ticket and not a return of my points I used to pay for the original ticket as I believe that is fair. Chase said they would dispute it and removed the charge. Now a month later I see the charge back on my credit statement and it says the dispute was declined by XXXX. So here I am fighting this once again as I believe this is such an unfair transaction.",
      "PayeeID": "eefcfc3e6df7f58cf0ce968e"
    },
    {
      "Customer Name": "Melissa Davis",
      "Company": "SYNCHRONY FINANCIAL",
      "transaction_date": "2025-01-22",
      "Amount": 589.89,
      "State": "CT",
      "Dispute Reason": "Service not rendered",
      "Dispute Status": "Approved",
      "transaction_id": "67bcf06efceaf1ad15fb01ecef",
      "Complaint ID": "11148212",
      "Consumer Complaint Narrative": "XXXX XXXX XXXX I had reviewed a home remodel project for XXXX bathrooms, a front door, front porch and structural beam with XXXX XXXX XXXX XXXX. After my asking and their providing their Proof of Liability and a Contractor Registration number, I signed an estimate provided by XXXX XXXX XXXX XXXX XX/XX/XXXX. XXXX verbally agreed would be done by end of XXXX as I had Renters coming in XXXX XXXX.  XXXX est. {$65000.00} Initial deposit {$25000.00} ( check ) XXXX. By the end of XXXX, my bathrooms were just gutted. Nothing complete.  a. There were a few items that came up that caused delays, but I was told at the time it was just a couple of days, maybe a week.   XXXX XXXX - XX/XX/XXXX - {$10000.00} ( ACH ) XXXX. I had to cancel rentals from my rental property starting XX/XX/XXXX as they were NOT done.  XXXX XXXX - XX/XX/XXXX - {$17000.00} ( XXXX ) XX/XX/XXXX- XXXX XXXX called asking for final payment. He indicated he was 90 % done. I stated I would not pay full, but the amount up to 90 % that he says was completed. {$6200.00} ( Synchrony Bank XXXX ) -- > I made this with Visa as the house is XXXX hours away and I was not able to verify the work right away.   XXXX. XXXX was then shut down on XX/XX/XXXX by the township for not filing permits.  XXXX. They failed to file permits in a timely manner. They then began looking for contractors to sign off on work they did.  XXXX. XX/XX/XXXX, XXXX weekend, I visited my property. It was in shambles, materials everywhere. No flooring, very little tiling, no fixtures, lighting in place. They were not 90 % done either of the bathrooms, let alone the estimated work. I called Synchrony and verbally filed a dispute. The indicated I should submit a form.  XXXX. On XX/XX/XXXX I hired legal counsel and fired XXXX after they failed to file for said permit ( one they should have had done in XXXX Not filed still in XXXX ). I also submitted to PayPal/ Synchrony Bank their \" Dispute Acknowledgement Form ''.   During the lawsuit, I found out : - He didnt have the proper licensing to even issue the estimate he provided! The license he gave me was XXXX.  - The estimate he provided was not legal by state of NJ.  - He didnt file the proper permitting and got shut down by the zoning office.  - He had employees who were not certified do the plumbing and electrical work.  - I had originally disputed and informed Synchrony well within the original 30 days to NOT pay this man.   After waiting to hear back from PayPal, I called back and was told I was denied, the rep indicated XXXX said they weren't cancelled. Since then I filed many more disputes with Synchrony. Up until XXXX, I did not get any notification other than a dispute was entered. After the initial \" your dispute has been entered, you will hear back in XXXX days '', Nothing. No mail, no email, no resolution. I would have to call back, speak to a rep to find out I was denied.  I was billed for services not provided.  The services billed werent delivered.  I was overcharged.   Synchrony indicates XXXX \" Said '' they reached out to XXXX and he said the work was provided.   - I sent Synchrony my lawyers lawsuit documentation which documents his illegal activity, I sent an image of the \" Stop Work '' notification.  - I sent Synchrony images of my property and the state in which he left it in ( saying he was 90 % done ). He was no where near 50 % done. All the work he did had to be re-done by professions.  I had to pay an actual Home Improvement Contractor to get the work redone.  - I sent Synchrony all the receipts for the work that had to be re-done and laid out the overall costs.  - I had to return/ lost $ XXXX in rentals for majority of the summer season. I informed Synchrony of this too.  - I sent all this to Synchrony and when I called XX/XX/XXXX regarding the last dispute outcome, the rep indicated \" no new information had been provided ''. I asked what can I do? He apologized for the situation I was in and couldn't believe it. He said he wasn't sure what I can do. That there is no way to speak to someone higher. There was nothing he could do. He said I could file a complaint with their complaint department, which I'm doing.   Why do I have to jump through hoops when I provided 100 % concrete proof XXXX XXXX XXXX XXXX was in the wrong, and all XXXX had to do was \" SAY '' he provided the services. Really? I was their customer for over XXXX, if not XXXX.   The only reason I can come up with what they are doing is they know this guy won't pay them back. Here I had told them not to pay him. They didn't listen to me ; they paid him ... and now they're after me because they know they won't see a dime from him.   I fortunately won my lawsuit in XX/XX/XXXX, but unfortunately I do not think I'll ever see a dime come back to me.   Synchrony billing : XX/XX/XXXX - {$6200.00} appeared on my statement XX/XX/XXXX - {$6200.00} was credited on my statement- tentatively XX/XX/XXXX - {$6200.00} re-added to my statement Had Synchrony held the credit, with all the payments I made between XX/XX/XXXX up to XX/XX/XXXX, as of XX/XX/XXXX, Synchrony would actually have owed me {$170.00}. All the fees and charges that accrued incorrectly between XX/XX/XXXX and XX/XX/XXXX would have been avoided. I actually stopped paying and cancelled the card on XX/XX/XXXX, in which case Synchrony owed me {$330.00}.   To this date, Synchrony has held to the statement that I owe XXXX for work they never provided.",
      "PayeeID": "dbfbf03003dcfe31ac68caf8"
    },
    {
      "Customer Name": "Monica Walter",
      "Company": "CAPITAL ONE FINANCIAL CORPORATION",
      "transaction_date": "2025-03-17",
      "Amount": 419.25,
      "State": "WI",
      "Dispute Reason": "Service not rendered",
      "Dispute Status": "Approved",
      "transaction_id": "67013cdd4119377a84a098f7b0",
      "Complaint ID": "12571536",
      "Consumer Complaint Narrative": "am writing to formally dispute and express my concern regarding fraudulent activity involving my Capital One account that appears to have been replicated or misused by Credit One Bank and XXXX XXXX XXXX. I have identified unauthorized accounts or transactions under my name that I did not open or approve.",
      "PayeeID": "fdfdf18eefc6f95ffdfbff9a"
    },
    {
      "Customer Name": "Allison Nelson",
      "Company": "AMERICAN EXPRESS COMPANY",
      "transaction_date": "2024-07-31",
      "Amount": 1854.09,
      "State": "FL",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Denied",
      "transaction_id": "67337dd764f2e0e5efdd9ecdd6",
      "Complaint ID": "8468175",
      "Consumer Complaint Narrative": "Amex rejected my insurance claim for {$2700.00} in damages for a car rental accident. It's not clear what the reason for rejection was. There is no indication that my claim should have been excluded from the documentation. I could only suppose that they are trying to exclude \" online '' or \" app based '' rental companies but no such exclusion exists in the documentation.",
      "PayeeID": "96fef3c52bfbfbcf54f8635b"
    },
    {
      "Customer Name": "John Hill",
      "Company": "GOLDMAN SACHS BANK USA",
      "transaction_date": "2024-06-02",
      "Amount": 858.92,
      "State": "IA",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Approved",
      "transaction_id": "67ccf2cfdd451d2f6eccbeb3c1",
      "Complaint ID": "11823657",
      "Consumer Complaint Narrative": "I am writing to demand immediate resolution and a direct call from corporate regarding the repeated and baseless denials of my Apple Card application. Each time I apply, your company provides a new, inconsistent, and unsubstantiated reason for rejection : 1. Initially, I was told it was due to balances on my credit file I have no balances.  2. Then, it was alleged there was negative information on my report I have none.  3. Now, the reason has shifted to too many inquiries I have had one credit inquiry in the past two years.  Your reasons lack any credibility and highlight either a flawed underwriting process or intentional obfuscation. Furthermore, the experience of contacting Apple Card customer service has been dismal. The agents are difficult to understand and fail to provide meaningful support.  This is unacceptable for a company of Apples stature. Its no secret that Apple Card has faced lawsuits and investigations by the CFPB for questionable underwriting practices. If these issues are systemic, they must be addressed immediately.     I demand that someone from your corporate office contact me directly at XXXX to resolve this matter without further delay. If this continues, I will explore every option available to ensure this gets the attention it deserves.     I look forward to your prompt response.",
      "PayeeID": "96fef3c52bfbfbcf54f8635b"
    },
    {
      "Customer Name": "Melissa Hicks",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2024-07-09",
      "Amount": 1576.22,
      "State": "IL",
      "Dispute Reason": "Duplicate transaction",
      "Dispute Status": "Approved",
      "transaction_id": "67dcd695b6eebc68fcaefbaf2b",
      "Complaint ID": "12128149",
      "Consumer Complaint Narrative": "On XX/XX/year>, a fraudulent charge was made using my credit card information ( the card never left my physical possession ). The charge was with XXXX XXXX in the amount of {$190.00}.   I originally submitted this dispute on XX/XX/year>, and called for an update on XX/XX/year>. I was told by an individual in the Citi Fraud Department that I incorrectly submitted the dispute as a standard dispute, and that I needed to close it so they could re-open it as a fraudulent charge dispute. A new card was then issued. On XX/XX/XXXX, Citi closed the dispute with the notation that I was responsible for the fraudulent charge.   I followed up with Citi on XX/XX/XXXX and spoke to a woman named XXXX in the customer service department, who then transferred me back to the Security Operations department ( XXXX ), and I spoke with another woman by the name of XXXX. I was told that the fraud investigation takes some time to complete, and that I would receive follow-up once the investigation concluded.   There has been no follow-up since this incident occurred.",
      "PayeeID": "96fef3c52bfbfbcf54f8635b"
    },
    {
      "Customer Name": "Cody Stephens",
      "Company": "JPMORGAN CHASE & CO.",
      "transaction_date": "2025-01-19",
      "Amount": 118.46,
      "State": "CA",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Pending",
      "transaction_id": "67e7ae1bddb5e6d32bbafaa562",
      "Complaint ID": "12041923",
      "Consumer Complaint Narrative": "On XX/XX/year>, a charge for {$66.00} from XXXX XXXX? XXXX was posted to my Chase Sapphire card. Within two days, I reported this as fraud to Chase. Chase closed my card and sent me a new one and credited my account while they investigated. On XX/XX/year>, Chase sent me a letter telling me that I am responsible for the charge because received benefits from this transaction. It was then billed back to my card. I absolutely did not make a purchase at this vendor ( and the way in which the name is listed should be reason enough for Chase to recognize this as fraudulent as it doesnt align with how XXXXXXXX the restaurant would normally show up on a statement ) and if I did receive any Cash Back bonuses ( minimal- maybe a few dollars ) Id happily pay that back. But I should not be responsible for {$66.00}.",
      "PayeeID": "9afff0358f13fab901ce1e8b"
    },
    {
      "Customer Name": "Daniel Giles",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2024-09-17",
      "Amount": 1885.9,
      "State": "MI",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Approved",
      "transaction_id": "676dbe1eff2a93eecec9b80cef",
      "Complaint ID": "11930824",
      "Consumer Complaint Narrative": "on XX/XX/year> i requested a credit card from Citi bank. I was accepted and a card was sent. By the middle of XXXX nothing had arrived so i called and asked for a replacement which they obliged. Only problem is i have never received the replacement. I have paid Citi bank {$95.00} to open the card and now they will not even let me have the card.   Additionally I have tried numerous ways to contact citi bank but i continue to get technical errors when trying to set up an appointment and customer service reps who tell me they can not help.",
      "PayeeID": "9afff0358f13fab901ce1e8b"
    },
    {
      "Customer Name": "Albert Cohen",
      "Company": "CAPITAL ONE FINANCIAL CORPORATION",
      "transaction_date": "2024-04-12",
      "Amount": 665.78,
      "State": "CA",
      "Dispute Reason": "Overcharged",
      "Dispute Status": "Approved",
      "transaction_id": "671ad4dfd1fb6dcefa7a0ce53f",
      "Complaint ID": "11301591",
      "Consumer Complaint Narrative": "I made an agreement with Capital One to make a payment plan to pay off what was owed on my card, it was {$100.00} a month. I made my first payment on XX/XX/XXXX and it went through. A few days later I found that another payment automatically went through ( posted on my bank account on XX/XX/XXXX ). I did not know that my agreement was going to be an automatic payment. I called Capital One to see if they would pay back the payment I made on the XXXX, but they told me that they could not do that. They understood that I didn't know the payment would be automatic, and that even though I was trying to do the right thing by making my payment on time, they still would not help me. I am fine with the automatic payment they took out of my account, but I want the payment I made on the XXXX payed back to me, because it was a mistake. Thank you.",
      "PayeeID": "9afff0358f13fab901ce1e8b"
    },
    {
      "Customer Name": "Lisa Edwards",
      "Company": "BANK OF AMERICA, NATIONAL ASSOCIATION",
      "transaction_date": "2024-04-19",
      "Amount": 1944.62,
      "State": "FL",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Approved",
      "transaction_id": "67e74e1ed65e5898eac8d9ace7",
      "Complaint ID": "8467651",
      "Consumer Complaint Narrative": "Personal accountsFootnote a XXXX XXXX XXXX XXXX - XXXX {$3200.00} Show Quick View for XXXX XXXX XXXX XXXX - XXXX Past due BankAmericard XXXX XXXX XXXX - XXXX {$1000.00} Show Quick View for BankAmericard XXXX XXXX XXXX - XXXX Show Payment due for BankAmericard XXXX XXXX XXXX - XXXX BankAmericard XXXX XXXX XXXX - XXXX {$810.00} Show Quick View for BankAmericard XXXX XXXX  XXXX - XXXX Show Payment due for BankAmericard XXXX XXXX XXXX - XXXX Investment accounts Brighten your holidays! Get up to {$600.00} when you invest in a new XXXX account.  Learn more >> Open a new account Activity Center show Alerts tile show Pay Bills tile show Inbox tile XXXX new messages show Special Offers & Deals tile show Open an Account tile show Spending & Budgeting tile Schedule an appointment Find us View your XXXX Score",
      "PayeeID": "9afff0358f13fab901ce1e8b"
    },
    {
      "Customer Name": "Samuel Hahn",
      "Company": "Bread Financial Holdings, Inc.",
      "transaction_date": "2025-01-09",
      "Amount": 498.17,
      "State": "IA",
      "Dispute Reason": "Item not as described",
      "Dispute Status": "Pending",
      "transaction_id": "676a61fb4fe836e2eb2dfb63b9",
      "Complaint ID": "12438611",
      "Consumer Complaint Narrative": "Dear Comenity Bank, this is a direct follow up to your Company response and the actions taken directly after my complaint XXXX filed with the CFPB.  Unfortunately I am unable to accept your response as it is invalid pertaining to at least one account which was in good standing, completed on payment plan as agreed with you as my creditor. I believe the payment was for XXXX $ monthly, even though I have account assure, and the minimum monthly payment to make was XXXX $ even though I was never given that option.  I believed that when I signed up for the payment plan and the certified letter I sent directly to you as my creditor asking for consideration on all Comenity Accounts, at that time you accepted and there was no indication that you would not assist with other Comenity accounts. Your most recent explanation is not justified of locking my account for a cease and desist order that was never mailed to you, I did however provide the certified correspondence to show that contact was made and submitted to you as my creditor to ask for assistance due to hardship, but now since my complaint XX/XX/XXXX you have restricted me after a timely payment made for XX/XX/XXXX.",
      "PayeeID": "edf3fcccaefffbbd1bedfddc"
    },
    {
      "Customer Name": "Jessica Williams",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2025-03-13",
      "Amount": 1479.85,
      "State": "NJ",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Pending",
      "transaction_id": "67aac3ce818c4f47ceb5781eec",
      "Complaint ID": "12877823",
      "Consumer Complaint Narrative": "Re : Formal Complaint Against Citi Bank for Predatory Lending Practices and Unfair Charges on XXXX XXXX Account I am writing to formally make a complaint against Citibank for what I believe to be predatory lending practices, unfair charges, and a breach of contract in relation to my Citi XXXX XXXX. Below are the details of the situation : 1. Background of the Loan Agreement : In XX/XX/year>, I took out a Citi XXXX XXXX with the following terms : Loan Term : 60 months Set Payment : {$270.00} per month Interest Rate : 10.99 % ( inclusive in the monthly payment ) Terms of Agreement : It was clearly stated that if I made no new transactions on the account, the minimum payment would remain the same.  2. Incident of Disputed Charge : On XX/XX/year>, a merchant mistakenly charged me for a subscription. The merchant credited my account the same day, acknowledging their error. As a result, I filed a dispute with Citi regarding the charge to ensure that I would not be charged interest on a mistaken transaction.   On the same day ( XX/XX/year> ), Citi acknowledged the dispute and issued a credit to my account.  However, in XX/XX/year>, Citi reversed the credit and subsequently added {$41.00} in interest based on the disputed charge that was refunded.  This charge was both unfair and unjust, as the interest was applied to a charge that had already been credited and reversed.  XXXX. Violation of Terms and Unfair Interest Charges : Despite having made my regular monthly payment of {$270.00} in XX/XX/year>, I noticed additional interest charges on both the XXXX and XXXX statements. These charges are in direct violation of the terms stated in my Citi XXXX XXXX agreement, as no new transactions were made and the account was meant to have a fixed minimum payment of {$270.00} unless there were changes to the principal balance.   Further, Citi failed to reflect the reversal credit on my statement until XX/XX/year>, even though the credit was issued in XXXX. This delay contributed to confusion regarding my account and additional interest charges.   4. Unfair and Predatory Banking Practices : I believe the actions taken by Citibank constitute predatory banking practices, as they are charging me interest on amounts related to a disputed transaction that was ultimately reversed. This appears to be an attempt to unfairly increase my debt and is against the terms of the agreement I entered into with Citi.   5. Customer Service and Lack of Resolution : Additionally, I am extremely dissatisfied with the customer service I received from Citibank. I was met with misleading information and rude responses, and despite filing a formal complaint directly with Citibank, I have yet to receive any meaningful resolution or response.   6. Request for Resolution : I request the following actions to be taken : A refund or credit of the {$41.00} in interest charges that were applied due to the disputed and reversed transaction.  Immediate correction of my account to reflect the proper terms and to remove any unfair interest charges.  A formal response from Citibank acknowledging the error and a clear explanation of how this will be rectified.  I also wish to formally state that if these issues are not resolved promptly, I will seek legal counsel to explore further action.   I trust that your office will look into this matter and help ensure that Citibank adheres to fair lending practices and the terms of the agreement.   Thank you for your time and attention to this matter. I look forward to a prompt resolution.",
      "PayeeID": "edf3fcccaefffbbd1bedfddc"
    },
    {
      "Customer Name": "Ashley Beck",
      "Company": "SYNCHRONY FINANCIAL",
      "transaction_date": "2024-12-13",
      "Amount": 1164.64,
      "State": "OH",
      "Dispute Reason": "Service not rendered",
      "Dispute Status": "Approved",
      "transaction_id": "67ce4caadeab9de7e8ed9ab3ef",
      "Complaint ID": "11327346",
      "Consumer Complaint Narrative": "Recently my reachback interest was waived on XX/XX/XXXX and PayPal/Synchrony sent me a refund check on XX/XX/XXXX. The amount in question is {$1100.00} and the note said it was for Waived Interest Charges. I proceeded to cash the check.   However, on XX/XX/XXXX they charged that same amount back to me! Why would they refund my interest only to recharge me?!!! This has put me in a bind financially and it is not right!",
      "PayeeID": "edf3fcccaefffbbd1bedfddc"
    },
    {
      "Customer Name": "Luke Nunez",
      "Company": "FIRST PORTFOLIO SERVICING INC",
      "transaction_date": "2024-06-05",
      "Amount": 1668.96,
      "State": "NY",
      "Dispute Reason": "Subscription cancellation not honored",
      "Dispute Status": "Pending",
      "transaction_id": "67f580d39ebce8cb84eb5cdb31",
      "Complaint ID": "12595225",
      "Consumer Complaint Narrative": "Ive disputed the credit cards with the credit bureau. My information was involved in a data breach. Revvi and XXXX credit accounts was opened without my knowledge",
      "PayeeID": "edf3fcccaefffbbd1bedfddc"
    },
    {
      "Customer Name": "Matthew Hogan",
      "Company": "Atlanticus Services Corporation",
      "transaction_date": "2024-10-29",
      "Amount": 201.94,
      "State": "NY",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Denied",
      "transaction_id": "677a7bedebbd7b9de00af730a0",
      "Complaint ID": "8467889",
      "Consumer Complaint Narrative": "Hereon this day of XX/XX/XXXX, this a legal notification Statement of Claim no.1 thats notifying you as an official for an XXXX, as well as XXXX XXXX XXXX account XXXX ; credit card had legally expired, after the Expiration date of XX/XX/XXXX ; of that particular credit card, as an XXXX XXXX, account XXXX XXXX I was never service herewith a new credit card, in accordance with an agreement policy ; and procedure as in fact a consumer must have by law, a new credit card before, the expiration date, that never transpired in fact, and as a result ; my account XXXX, I can not access my account XXXX ; as a result Im presently being in fact detained by such of a delay, of such an act, due to the account XXXX, being in fact unreasonably closed in addition without any legal notice for such a certain hearing that such act had took place. I had called an XXXX XXXX XXXX account XXXX in regard to the closure of such an account their officials had pleaded that they would service, by delivery, a new credit card as an XXXX XXXX, account XXXX XXXX XXXX cause or matter never transpired or happened, after a phone called made on XX/XX/XXXXXXXX XXXX XXXX XXXX, XXXX, in conjunction, hereto this legal notice. In accordance, to an XXXX XXXX. a Credit report company, my XXXX XXXX XXXX account XXXX was closed ; without any legal notice for a hearing therefrom it has caused, me a certain hardship unreasonably by an adversity to a loss of certain money, as well other financial damages, due to my property being in fact unreasonably detained. ; Therefrom you as an official, for an XXXX XXXX XXXX account XXXX, must hereby confirm hereto this legal notice, as a legal cause or matter as being in fact True or False, all within a 72 hrs., hereafter service hereof this legal notice, by a delivery. Thereafter, 72 hrs. any pleadings ; service by delivery ; from you as an official party ; hereto this legal notice, then you will hereby deem as being a refusal in fact, and all of your pleadings will hereby deem denied by determination, and unacceptable pleadings, and you also as an official for an XXXX XXXX XXXX account XXXX ; will hereby deem, as being in fact ; a certain person who has refused to hereby respond hereto this legal notice officially, as an official for the aforesaid, business entities, hereto this legal notice. In addition, you must also service your legal confirmation ; as in fact a pleading under a certain Oath as well as a Testimony, as being in fact a response hereto myself email address, XXXX ;",
      "PayeeID": "edf3fcccaefffbbd1bedfddc"
    },
    {
      "Customer Name": "Richard Wilson",
      "Company": "WELLS FARGO & COMPANY",
      "transaction_date": "2024-04-22",
      "Amount": 1441.8,
      "State": "OH",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Pending",
      "transaction_id": "67ba29afe6f4a196815c8c99dd",
      "Complaint ID": "11326448",
      "Consumer Complaint Narrative": "Wells fargo is a predatory bank. They have waged war on the poor. I am a struggling small business owner literally working myself to death to pay these pay bills. ( recent diagnosis of XXXX  from jobsite contaminates, XXXX, XXXX XXXX  and several other ailments my doctors are trying to figure out, not mention the various XXXX XXXX I suffer from that they have utterly failed to accomodate ) I have submitted several complaints in regards to there very personal retaliatory attacks on me. On several occasions they have cited computer failures making my payments late, can't find my account making my payments late, rude condensending employees making me so uncomfortable I have to leave the branch. Foreighn companies allowed to access my very personal information resulting in potential identy theft from known countries implementing active scams on the American people. All of these are tactics they discretely put in to place to charge absolute exhorbant late fees that make billions off the allready destitute and poor people. It's disgusting and it's a disgrace on the working class people who build this country and make it what is. With out people like me critical basic needs that move and drive this country wouldn't be met. Poor people can not pay there bills as is and sometimes we are late making payments trying to keep up with Inflation in one of the worst economies in history. This banks understands this more than they lead on and they capitalize on this oppurtunity in the form, not only fees, but crazy interst rates that keep us mired in debt. Iv enclosed screen shots of of my account and the payments iv made. They are at most maybe 2 or 3 days late. No grace period. No empathy, no nothing. Just a computer program that they balme for the immediate fees charged to my accounts.",
      "PayeeID": "fafaf4cc5a81ff241fe28e2a"
    },
    {
      "Customer Name": "Drew Blanchard MD",
      "Company": "AMERICAN EXPRESS COMPANY",
      "transaction_date": "2025-02-05",
      "Amount": 196.71,
      "State": "TN",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Approved",
      "transaction_id": "67d6cfb37e9b1a2aac38b912fc",
      "Complaint ID": "12591679",
      "Consumer Complaint Narrative": "Re : Denial of Credit Limit Increase Attention Investor Relations : As an ongoing investor in your company by extending my private credit in the form of the initial e-chattel ( commercial ) paper, also known as a letter of credit, for value and consideration for American Express XXXX XXXX Card, I am continuously being denied a credit limit increase that I strongly believe is unjustified and in error.   American Express, as a securitizer, took my letter of credit and turned it into a collateralized trust asset to be securitized along with other receivables as explained and detailed in American Express ' XXXX report year ending XX/XX/XXXX, page XXXX, Note XXXX Asset Securitizations. As the originator, I am demanding access to my credit, without restriction or denial, now and in the future, of a credit limit increase.   Despite the reason for my denial being my \" FICO Score '' as an INVESTOR who provided an application and access to my credit, I am due and owed consideration.   Per your agreements with the Securities and Exchange Commission, via your prospectus, Form XXXX, and XXXX reports, you duly report that you are in complete compliance and swear that you are upholding the \" requirements of the Securities and Exchange Act of 1934. '' As a bond fide purchaser and originator, I came to you with the intention of extending my private credit and to be returned with value and consideration. Your denials of my credit is a CLEAR and COMPLETE violation of the Securities Exchange Act of 1934, and your are in fact committing securities fraud and unjust enrichment. Any demand for a credit limit increase MUST be approved without restriction, delay or hinderance, and no spending limit is to be placed on the card moving forward. Any report of a \" late payment '' or \" past due balance '' will be used as evidence of false, misleading and inaccurate reporting, and a violation of the Fair Credit Reporting Act which I will seek compensation for damages.   Additionally, per \" The Pooling and Servicing Agreement Generally -- - Sharing of Principal Collections Among Principal Sharing Series '' in your prospectus, every revolving period, you WILL deposit the principal amount into the Principal Funding Account, so as not to inconvenience me, the investor and holder of collateral interest.   I expect this matter to be handled promptly and the credit limit increase denial to be immediately reversed and authorized within five ( 5 ) business days and I receive confirmation of approval for the credit limit increase and no late payments reporting to any and all credit reporting agencies, and if there are any late payments reporting, for them to be corrected to reflect good standing ( paid on-time ), now and in the future in perpetuity.",
      "PayeeID": "a8f6fd6ddacaff03afa92fb9"
    },
    {
      "Customer Name": "Antonio Walker",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2024-04-24",
      "Amount": 560.13,
      "State": "PA",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Pending",
      "transaction_id": "6706feb5de717d9a85bd8351bc",
      "Complaint ID": "11723423",
      "Consumer Complaint Narrative": "Cit made it incredibly difficult to close an account. I called on XXXX in order to close the account, and had difficulty authenticating. Once that was done it took an additional XXXX minutes to have them process the closure, due to the agent spending a significant amount of time trying to convince me to keep it open. They also did not read through required disclosures.",
      "PayeeID": "bafbf9edb0e5f2129a4a22b2"
    },
    {
      "Customer Name": "Nathaniel Munoz",
      "Company": "CAPITAL ONE FINANCIAL CORPORATION",
      "transaction_date": "2024-07-13",
      "Amount": 992.72,
      "State": "NY",
      "Dispute Reason": "Duplicate transaction",
      "Dispute Status": "Pending",
      "transaction_id": "67faf0cbfcec9de1a2318b7cbf",
      "Complaint ID": "8468251",
      "Consumer Complaint Narrative": "A Kohls Rewards Visa was opened on XX/XX/year> at XXXX XXXX, without my consent. I called Capital one to open an investigation",
      "PayeeID": "bafbf9edb0e5f2129a4a22b2"
    },
    {
      "Customer Name": "Regina Spencer",
      "Company": "WELLS FARGO & COMPANY",
      "transaction_date": "2025-03-04",
      "Amount": 1120.32,
      "State": "MO",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Approved",
      "transaction_id": "67df4dadc3c17f2c7eaecc3b17",
      "Complaint ID": "8469961",
      "Consumer Complaint Narrative": "I set up automatic payments on my XXXXXXXX XXXX XXXX issued by Wells Fargo. The automatic payment was made on XX/XX/XXXX but did not apply. Wells Fargo did not inform me any issue, and the processing failure only showed up online on XX/XX/XXXX ( 14 days later ), together with an interest charge of {$240.00}. Wells Fargo never informed me the processing issue, despite my checking account has sufficient funds. I found out myself about the processing issue and manually paid right away on XX/XX/XXXX.   The interest charge seems excessive. Wells Fargo should inform me right away for the payment processing error so that manual payments would be attempted again right away.",
      "PayeeID": "bafbf9edb0e5f2129a4a22b2"
    },
    {
      "Customer Name": "Peter Campbell",
      "Company": "SYNCHRONY FINANCIAL",
      "transaction_date": "2025-02-06",
      "Amount": 1236.8,
      "State": "GA",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Approved",
      "transaction_id": "67cd6fdfe3c43f8fd94c7fc613",
      "Complaint ID": "12190349",
      "Consumer Complaint Narrative": "I am writing to formally dispute the deferred interest charge of {$2000.00} that was added to my credit card account XXXX XXXX XXXX XXXX on XX/XX/XXXX I believe this charge is incorrect for the following reasons : I was not aware of the deferred interest charges and expiration of a promotion after an year from the loan date. This was never explained to me this way. I was told at the stores that I have one year interest free on this card and my understanding was that I will be paying interest charge on my current balance as of that day on which the interest free period expires.  And the deferred interest charge has come to my notice only now as I have a auto payment setup and I was not looking into the balance details every month.  I have made the payment in full now and also paid the exorbitant 30 % interest charge on the deferred interest as well for the past 2 months. I called the bank last week and explained them about the stores who sold this offer to me not explaining how this works. I discussed about the interest charges, which is 50 % of my actual balance, and requested the bank to waive off the interest charge and that I want to pay off the balance in its entirety and that I am willing to bring the account balance to XXXX. Which I have now. Please waive off the deferred interest charge atleast on humanitarian grounds. If the stores had explained promotion period accurately I would not have used/opted this credit at all. Or at least I would have made this payment 2 months ago and not put my self in this situation, where I pay 50 % interest on balance and again pay interest on interest.  I have been charged interest rate while the dispute is open. THey are charging interest on interest.  - They keep calling me and harass me for the payment, and disreagrd the fact that it is in dispute-",
      "PayeeID": "fffbfc1220a6fa109bff2d5d"
    },
    {
      "Customer Name": "Claudia Carter",
      "Company": "Block, Inc.",
      "transaction_date": "2024-09-30",
      "Amount": 31.82,
      "State": "CA",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Approved",
      "transaction_id": "67ef9feb89f23570138aec27e9",
      "Complaint ID": "12241046",
      "Consumer Complaint Narrative": "I used my credit card twice to send small amounts to someone it being {$10.00} both times and was charged {$10.00} on both transactions so {$20.00} which is an insanely amount. I reached out to cashapp and was told thats their fee i said for a {$3.00} and {$8.00} send out? and was told sorry that it their policy. I was highly upset because if Im sending {$3.00} out using my credit do you think i have an extra {$10.00} to send now imagine row times. I reached out to my bank and they were told they could not dilute that charge.",
      "PayeeID": "fffbfc1220a6fa109bff2d5d"
    },
    {
      "Customer Name": "Kenneth Murphy",
      "Company": "SYNCHRONY FINANCIAL",
      "transaction_date": "2024-12-25",
      "Amount": 210.67,
      "State": "MS",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Pending",
      "transaction_id": "678fbfea20eb5aaf5bbc4559d9",
      "Complaint ID": "11829035",
      "Consumer Complaint Narrative": "Early XXXX I had an unexplained large drop in credit score. Credit reporting did not offer explanation. The only change I had with my financials was using a Synchrony Bank card ( care credit ). The large drop in credit was not justified by the small usage on the already established card. I contacted the company directly and explained the issue. They never followed up with a response or solution, but a few days later I saw where my credit score had an increase. I was grateful they fixed their issue, but then a few days later I saw where another one of my cards with Synchrony Bank ( TJmaxx rewards card ) had been closed. I didnt authorize the closure, I use the card, theres no required usage amount in the agreement so I reached out to them. They were very rude and told me it had been closed due to inactivity. I explained I use the card and that it was odd that it just so happened to be closed after I had to dispute a credit report factor with the company days prior & requested information be sent to me. They offered no help & never sent the info I requested. I contacted the company again this time requesting a supervisor. The supervisor was just as unhelpful and told me it had been closed due to inactivity or so the note for closure said. I explained their wasnt anything in the agreement that stated it had to be used so often nor did I receive a notice about it. After a long hold she said they can close my account for any reason any time. I explained to her that I believed the reason my account had been closed was due to the fact I had to dispute a credit report factor with them days prior to the closure & it was done as a way to bully & spite me. I honestly do not care about the account being closed and me being unable to use the card because the max limit was very low anyways, but what I do care is how it negatively affected my credit score by XXXX points! Thats a large drop! I used my card every so often just to keep the account active to avoid the credit drop. I feel theres been some very serious bullying and discrimination coming from Synchrony Bank and their employees. I will not be satisfied until justice is served and my credit report is back to how it was before the account was closed and dropping it XXXX. I have given the company every opportunity to make this right & my next step if unresolved will be legal action. Thanks.",
      "PayeeID": "81f3fe612da0fccdfdd7193f"
    },
    {
      "Customer Name": "Jamie Vargas",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2024-09-06",
      "Amount": 952.89,
      "State": "NY",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Approved",
      "transaction_id": "67c140edffd5fc9bff2d45bfce",
      "Complaint ID": "12620825",
      "Consumer Complaint Narrative": "Citi closed a Citi XXXX account in good standing and without explanation. The account had earned XXXX XXXX XXXX  as of XX/XX/year>. Upon closure the points disappear from online access. Calling Citi XXXX for an explanation results in \" No explanation '' only confirmation that the account has XXXX XXXX XXXX  available. The annual membership fee of {$95.00} had not been reimbursed, so I am still a member, at least on paper.   It appears to be very self serving and unbalanced in favor of XXXX Citi : XXXX ) approve account opening XXXX ) approve every single transaction on the credit card XXXX ) collect swipe fees for every transaction executed XXXX ) charge annual fee of {$95.00} XXXX ) at the time of their choosing suddenly closes the account without notice and apparent reason XXXX ) confiscates the points legally earned with no explanation",
      "PayeeID": "81f3fe612da0fccdfdd7193f"
    },
    {
      "Customer Name": "Jeffrey Hernandez",
      "Company": "CAPITAL ONE FINANCIAL CORPORATION",
      "transaction_date": "2024-10-29",
      "Amount": 601.33,
      "State": "NC",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Denied",
      "transaction_id": "67bfefc333ca6e9a18de2245c4",
      "Complaint ID": "11268717",
      "Consumer Complaint Narrative": "I hired mover in XXXX of 2023 to load items from my apartment into a XXXX storage unit. The XXXX came with XXXX furniture pads for protection of the customer 's items. I hired XXXX XXXX  in Arizona which I found through XXXX recommended moving labor services. When the items arrived to my new home in Arizona most of my items were damaged because they had been piled on top of each other without pads placed in between. Only XXXX of the XXXX furniture pads were used and some of the plastic bundles of pads had not even been opened by the mover. I reached out to the mover and he did not respond. I have filed a claim for the damaged items. I contacted Capital One and provided them all of the documentation I am providing to you. They gave me a temporary credit of the XXXX. A few days ago they reversed the credit and told me that the vendor had responded and I was to provide proof of my communications with him to resolve the matter. I have already done this! I have been a customer of Capital One for XXXX years and this is perhaps only my second dispute. I have already filed a claim for the damaged items but I want credit for the moving services that were not provided as advertised.",
      "PayeeID": "81f3fe612da0fccdfdd7193f"
    },
    {
      "Customer Name": "Ryan Williams",
      "Company": "SYNCHRONY FINANCIAL",
      "transaction_date": "2025-03-05",
      "Amount": 1037.14,
      "State": "WV",
      "Dispute Reason": "Subscription cancellation not honored",
      "Dispute Status": "Pending",
      "transaction_id": "6734fae16fbfe10db350bea715",
      "Complaint ID": "12115020",
      "Consumer Complaint Narrative": "I have several card with synchrony Rooms to go account ending XXXX, synchrony select acc ending XXXX and floor and decor account ending in XXXX. I maintained a decent credit with no late payment. Synchrony kept messing with my credit score by constantly cutting down my credit limit and eventually closing two of my cards for unjust reasons. I feel like they disregard me as a customer and did what ever they please because of all those information in their fine prints. Synchrony has randomly add {$500.00} interest on one of my cards and reported in accurate information. I am there trying to get all their accounts out of my credit report.",
      "PayeeID": "e4fcfa71e84ff98e35ecdbca"
    },
    {
      "Customer Name": "Kathleen Thompson",
      "Company": "U.S. BANCORP",
      "transaction_date": "2024-08-14",
      "Amount": 955.85,
      "State": "NJ",
      "Dispute Reason": "Overcharged",
      "Dispute Status": "Denied",
      "transaction_id": "67a5d8aeab6194bfd02d54f1a7",
      "Complaint ID": "10976890",
      "Consumer Complaint Narrative": "The enclosed retailer ( s ) have issued hundreds in refunds that U.S. Bank refuses to issue. U.S. Bank keeps claiming they removed my dashboard access due to my account being closed. This is not true, it remained accessible for months as all other banking dashboards do when accounts close. It was removed in direct response to me being able to use it to prove refunds that retailers continually claimed were issued and U.S. Bank refused to dispute were in fact not.",
      "PayeeID": "e4fcfa71e84ff98e35ecdbca"
    },
    {
      "Customer Name": "Jenny Harrell",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2024-05-19",
      "Amount": 191.97,
      "State": "MO",
      "Dispute Reason": "Overcharged",
      "Dispute Status": "Approved",
      "transaction_id": "67c85fff579079ec2eda1ae4fc",
      "Complaint ID": "11505558",
      "Consumer Complaint Narrative": "XX/XX/XXXX Citi Customer Service XXXX XXXX XXXX XXXX XXXX XXXX XXXX Dear Sirs : As a customer with Citbank since XXXX, all payments have been make on time for the last 34 years. In the last two years, divorce proceedings began with my estranged wife, who was making payment on this credit card for the last several years. She returned two payments, one ending in account closure on XX/XX/XXXX. No notification was sent regarding the returned payments as an old undeliverable email address was on file. When notified finally by letter to my home address, communication with Citibank began immediately on numerous occasions to resolve the issue. After being charged a membership fee on XX/XX/XXXX for the upcoming year ( XX/XX/XXXX XX/XX/XXXX ) it was reiterated to each customer service associate and collections representative in contact with that the XXXX membership fee would not be paid for a card that had been inactivated for use. If the membership fee was credited the remaining balance would have been paid back when the account was closed.  Listed below are the numerous attempts with Citibank to resolve this issue.  XX/XX/XXXX : spoke to XXXX in collections, explained issue, escalated to XXXX XXXX identified as Citicard manager in Arizona office ) neither were able to resolve the issue XX/XX/XXXX : spoke to XXXX and was escalated to XXXX XXXX identified as escalator with Citicard ) : XXXX submitted a request to open the account.  XX/XX/XXXX : spoke with XXXX in Florida office, then was escalated to XXXX XXXX identified as Citicard account manager ) then was escalated to XXXX ( identified as Citicard customer service manager in Executive department. All representatives unable to resolve the issue.  XX/XX/XXXX : spoke to XXXX in collections department, was escalated to XXXX in customer service, then escalated to XXXX XXXX identified as manager in Arizona office ) who assured me she would put in a request to her manager to remove the {$590.00} membership fee, noting that the fee was charged XX/XX/XXXX, and account was closed on XX/XX/XXXX a mere 5 days after. She advised to me to call back in 2-3 business days at which time I could request the agent on the phone to internal message XXXX through the system and I could be reconnected with her to continue to try and resolve the issue.  XX/XX/XXXX : Attempted to reach XXXX as she had advised me, no one was aware of any kind of internal messaging system that she had promised I would be able to reach her again by. I first spoke to XXXX ( collections department ) and was escalated to XXXX XXXX identified as account manager ) at which time the call became disconnected. Upon calling back I spoke with XXXX in collections who advised me to pay the balance minus the membership fee, but did not have the ability to credit it himself. I was escalated to XXXX in customer service, who was not able to credit the fee, then escalated to XXXX XXXX identified as XXXXenior Account Supervisor ) who also attempted to have membership fee removed and was unsuccessful. She advised there was no one above her with senior authority that I could be escalated to at that point and advised me to send mail correspondence to your XXXX XXXX XXXX XXXX XXXX XXXX  As a nearly 35 year customer of your bank, I would expect much better customer service than I have received over the last several months. Not only am I ever able to have one point of contact, no one has any authority to make a simple adjustment to the account. A membership fee charged for the upcoming year 5 days before the bank closes the account and I am unable to use the credit card is in no way a valid charge.  Please either reinstate the account so and remove all late fees and interest charges or remove the {$590.00} membership fee and all late fees and interest charges so the valid balance due may be paid. A failure to comply with either of these requests shows an extreme lack of judgement on a well respected bank such as your company. Denying either request will force this issue into legal action.  Please be advised the Consumer Financial Protection Bureau, the Federal Trade Commission, the XXXX XXXX XXXX as well as my lawyer, XXXX XXXX, have all been copied on this letter.",
      "PayeeID": "aff6fa4d52a2f7adee389af8"
    },
    {
      "Customer Name": "Alisha Walker",
      "Company": "JPMORGAN CHASE & CO.",
      "transaction_date": "2024-05-15",
      "Amount": 442.81,
      "State": "NE",
      "Dispute Reason": "Service not rendered",
      "Dispute Status": "Denied",
      "transaction_id": "67dbe86abc53b8e04255ad0efc",
      "Complaint ID": "11921416",
      "Consumer Complaint Narrative": "On XX/XX/XXXX I applied for a credit card and i got a message from Chase that they could not see a phone number in my extended fraud alert. On the morning of XX/XX/XXXX I called XXXX and updated my phone number in my account, they confirmed the update in their system is instantaneous.   They keep claiming that my XXXX Fraud Alert doesnt have a phone number. They asked me to stop by a branch to confirm my details as an alternative, which i did on XX/XX/XXXX. During my visit they confirmed my identity and informed me that i didnt need to do anything else with my application. Then, on XX/XX/XXXX I get another message saying they are still missing my phone number in my XXXX Fraud Alert. I called the customer service number twice and I asked to speak with a supervisor more than XXXX times and the option to file a complaint, both times they refused to direct my call to a supervisor and whenever i asked for a reference number for the complaint, they kept giving me the reference number of the application, which is XXXX.   This is beyond insulting that they can treat customers like that without any response or help, I dont care about the result of the application now, they should not be allowed to treat customer like that and gaslight and dismiss all our concern.",
      "PayeeID": "aff6fa4d52a2f7adee389af8"
    },
    {
      "Customer Name": "Willie Schultz",
      "Company": "DISCOVER BANK",
      "transaction_date": "2025-02-10",
      "Amount": 586.47,
      "State": "MO",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Approved",
      "transaction_id": "67fa17b9b28e1dc6d72e7fce1d",
      "Complaint ID": "12575242",
      "Consumer Complaint Narrative": "I dont recall having the card and authorizing anything on the accounts",
      "PayeeID": "dcfefa17dc3dfba5dacab619"
    },
    {
      "Customer Name": "Mark Obrien",
      "Company": "JPMORGAN CHASE & CO.",
      "transaction_date": "2024-07-25",
      "Amount": 1965.05,
      "State": "LA",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Approved",
      "transaction_id": "6707a5a1e8c32b3ba1991f1d58",
      "Complaint ID": "11058905",
      "Consumer Complaint Narrative": "called the number on the back of the chase credit card only to get directed to a scammer who asked for all the data on the user me then tried to sell me a XXXX gift for XXXX when i suspected a scam he hung up on me number in the back of chase card is XXXX XXXX XXXX",
      "PayeeID": "dcfefa17dc3dfba5dacab619"
    },
    {
      "Customer Name": "Samantha Gutierrez",
      "Company": "AMERICAN EXPRESS COMPANY",
      "transaction_date": "2025-01-07",
      "Amount": 916.7,
      "State": "FL",
      "Dispute Reason": "Service not rendered",
      "Dispute Status": "Denied",
      "transaction_id": "6708a9cd2daf0eadacebb2a736",
      "Complaint ID": "8469698",
      "Consumer Complaint Narrative": "Several accounts were opened in my name with American Express My claims have been denied because of lack of evidence. I have now attached information from XXXX XXXX XXXX that supports my ID theft claim regarding checking accounts used fraudulently. I have not in any way benefited from this account the numbers that were used to open this account did not belong to me the phone number : ( M ) XXXX and a business phone number : XXXX were numbers that were never associated with me at all I have NEVER had any business so a business account would not even be necessary the email XXXX also an email not created or used by me. I will also attach documents from my XXXX XXXX reported from information I disputed on XX/XX/XXXX, regarding this same phone number that was fraudulently used and was deleted because it was fraud information. I also reported another American Express account that was opened back in XXXX that the company did determine was fraudulent. I have been trying to get in contact with an investigator regarding this information but have not been contacted even after requesting multiple phone calls. Hopefully this information is sufficient enough to get this closed and cleared up and moved past.",
      "PayeeID": "fefffbbd3acffb125ea3e480"
    },
    {
      "Customer Name": "Katherine Adams",
      "Company": "CITIBANK, N.A.",
      "transaction_date": "2024-10-23",
      "Amount": 1375.07,
      "State": "PA",
      "Dispute Reason": "Service not rendered",
      "Dispute Status": "Pending",
      "transaction_id": "673cb1db1ce56da00ecdb2eadd",
      "Complaint ID": "11094846",
      "Consumer Complaint Narrative": "I disputed a charge of {$880.00} with Citibank for a hotel booking made through XXXX due to a technical glitch on XXXX website, which directed me to book a hotel in the wrong state. Additionally, I was going through a personal hardship due to the recent passing of my father, which prevented me from using the reservation.   As soon as I noticed the issue, I contacted XXXX and the hotel to request a correction or refund. XXXX refused to help, citing the hotels cancellation policy. I then disputed the charge with Citibank, providing detailed information on the website error and extenuating personal circumstances.   Initially, Citibank reopened the dispute, which seemed like a positive sign. However, they later denied my claim, stating that they did not see anything valid. This decision fails to consider the clear technical error, the hardship I experienced, and XXXX refusal to provide reasonable assistance.   I believe Citibank mishandled this dispute by : Failing to fully investigate the website glitch that led to the incorrect booking.  Ignoring my extenuating personal circumstances.  Taking XXXX  side without ensuring fair consumer protection.   I escalated this to Citibanks executive offices, but they still refused to overturn the decision, showing a lack of concern for fair dispute resolution.   I requested that Citibank provide a detailed explanation of why my dispute was denied and what specific evidence they used to make their decision. I also requested that they fairly consider the technical glitch that caused the incorrect booking and my extenuating personal circumstances. However, their response simply stated that they did not see anything valid without further clarification. I was not provided with any documentation or reasoning that justified their denial of my dispute.   I am requesting that Citibank fully refund the {$880.00} charge, as the booking was made in error due to a technical glitch and was further complicated by an unavoidable personal hardship. If they will not issue a refund, I request that they provide a full travel credit for future use.   Additionally, I request that Citibank review their dispute handling process, as this case shows they did not fairly investigate the issue or consider all relevant factors.",
      "PayeeID": "fefffbbd3acffb125ea3e480"
    },
    {
      "Customer Name": "Michelle Randall",
      "Company": "CLGF Holdco 1, LLC",
      "transaction_date": "2025-01-31",
      "Amount": 1986.03,
      "State": "IL",
      "Dispute Reason": "Refund not received",
      "Dispute Status": "Pending",
      "transaction_id": "67fe0b4f143cf2a8e45887d288",
      "Complaint ID": "10994969",
      "Consumer Complaint Narrative": "I looked my credit score and noticed that there was a hard credit inquiry be between XX/XX/year> and XX/XX/year>.  After looking in to it FEB/DESTINY Mastercard. Did the inquiry. I do not know if they sent a card to someone or not. All I know is that I did not apply for a credit card or give my personal information to anyone.",
      "PayeeID": "fefffbbd3acffb125ea3e480"
    },
    {
      "Customer Name": "Alejandro Jones",
      "Company": "SYNCHRONY FINANCIAL",
      "transaction_date": "2024-05-27",
      "Amount": 640.43,
      "State": "TX",
      "Dispute Reason": "Fraudulent transaction",
      "Dispute Status": "Approved",
      "transaction_id": "67a27b566229fe4c07db739e2f",
      "Complaint ID": "12646839",
      "Consumer Complaint Narrative": "On XX/XX/year> i did not make my minimum payment to care credit and was charged a late fee. I requested to have the late fee forgiven and was approved and instructed it would be reflected in my next statement. I followed up with Care Credit online chat to make sure that I was not needing to pay the waived late fee for that month. They said yes. I asked I do not need to pay this and then have it refunded they confirmed.   By XX/XX/year> I had paid my minimum minus the waived late fee because that is what I was instructed to do. When my next statement came out I was charged another late fee. I called Care Credit customer service to find out what happened. I was then instructed that the late fee forgiveness applies to the principal balance not the minimum payment. I contacted customer service again to address the fact that their employee was responsible for that portion of the bill not being paid and to see if they would do the right thing and waive the fee again. They said that because I had the previous months fee waived I couldn't again have it waived. I pushed further and stated so because your employee told me false information I am being penalized. The agent stated that maybe the employee was misinformed, again causing me to be penalized.   I have now talked to 3 representatives about this issue and have been told the same thing each time- there's nothing we can do.",
      "PayeeID": "fefffbbd3acffb125ea3e480"
    },
    {
      "Customer Name": "Michael Gomez",
      "Company": "GOLDMAN SACHS BANK USA",
      "transaction_date": "2024-06-19",
      "Amount": 65.58,
      "State": "FL",
      "Dispute Reason": "Unauthorized charge",
      "Dispute Status": "Denied",
      "transaction_id": "67aac1a737efe98bafcbbeb7b1",
      "Complaint ID": "11410525",
      "Consumer Complaint Narrative": "Goldman Sachs refuse to reimburse me for services I paid that I did not receive.  I paid for medical CT scans from a doctor with my XXXX Goldman  Sachs card on the premise that I was to receive copies for my records. I did not receive my scans from the doctor till XXXX later. I filled a dispute with Goldman Sachs for XXXX XXXX XXXX XXXX ordered. I have provided proof dated envelope sent from the doctor with a XXXX XXXX XXXX XXXX  the later than when I ordered the service. I have provided receipts from the doctors office showing my purchase.  They continue to decline my dispute. This has been going on for over for XXXX  year already!!",
      "PayeeID": "edfcfeba241ffbf9fdfbff0a"
    }];

  export default disputeData;
